[shell]
program = "/opt/homebrew/bin/tmux"
args = [ "new-session", "-A", "-s", "main" ]

[window]
dimensions = { columns = 200, lines = 50 }
padding = { x = 14, y = 10 }
resize_increments = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Bold" }
bold = { family = "JetBrainsMono Nerd Font", style = "ExtraBold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "ExtraBold Italic" }
size = 13.0
offset = { x = 0, y = 3 }

[mouse]
hide_when_typing = true

[colors.primary]
background = "#1e2127"
foreground = "#abb2bf"

[colors.normal]
black   = "#1e2127"
red     = "#e06c75"
green   = "#98c379"
yellow  = "#d19a66"
blue    = "#61afef"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#abb2bf"

[colors.bright]
black   = "#5c6370"
red     = "#e06c75"
green   = "#98c379"
yellow  = "#d19a66"
blue    = "#61afef"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#ffffff"
